//! `xtask bench-monorepo` — generate a synthetic 10k-file monorepo and
//! measure betterhook against `hk` and `lefthook` on identical configs.
//!
//! The harness only requires `betterhook` to be on PATH (the workspace
//! binary). `hk` and `lefthook` are probed at runtime — when missing,
//! the corresponding row is recorded as `n/a` rather than failing the
//! whole run, so an OSS contributor without those tools installed can
//! still benchmark our cold/warm path against itself.
//!
//! Outputs a Markdown table to `target/bench-results.md` plus the same
//! payload as JSON on stdout for CI consumption.

use std::fmt::Write as _;
use std::path::{Path, PathBuf};
use std::process::{Command, ExitCode};
use std::time::{Duration, Instant};

const FILES_PER_PACKAGE: usize = 2000;
const PACKAGES: &[&str] = &["alpha", "beta", "gamma", "delta", "epsilon"];

pub fn run(args: &[String]) -> ExitCode {
    let total_files = FILES_PER_PACKAGE * PACKAGES.len();
    eprintln!(
        "bench-monorepo: generating {total_files} files across {} packages",
        PACKAGES.len()
    );

    let keep = args.iter().any(|a| a == "--keep");
    let tmp = match tempdir() {
        Ok(d) => d,
        Err(e) => {
            eprintln!("bench-monorepo: failed to create tempdir: {e}");
            return ExitCode::from(1);
        }
    };
    let repo_dir = tmp.join("repo");

    if let Err(e) = generate_repo(&repo_dir) {
        eprintln!("bench-monorepo: generate_repo failed: {e}");
        return ExitCode::from(1);
    }

    let mut rows: Vec<Row> = Vec::new();
    rows.push(measure(
        "betterhook (cold)",
        &repo_dir,
        &["betterhook", "run", "pre-commit"],
    ));
    rows.push(measure(
        "betterhook (warm)",
        &repo_dir,
        &["betterhook", "run", "pre-commit"],
    ));
    if which("hk") {
        rows.push(measure(
            "hk (cold)",
            &repo_dir,
            &["hk", "run", "pre-commit"],
        ));
        rows.push(measure(
            "hk (warm)",
            &repo_dir,
            &["hk", "run", "pre-commit"],
        ));
    } else {
        rows.push(Row::not_available("hk"));
    }
    if which("lefthook") {
        rows.push(measure(
            "lefthook (cold)",
            &repo_dir,
            &["lefthook", "run", "pre-commit"],
        ));
        rows.push(measure(
            "lefthook (warm)",
            &repo_dir,
            &["lefthook", "run", "pre-commit"],
        ));
    } else {
        rows.push(Row::not_available("lefthook"));
    }

    let table = render_table(total_files, &rows);
    if let Err(e) = std::fs::write("target/bench-results.md", &table) {
        eprintln!("bench-monorepo: failed to write target/bench-results.md: {e}");
    } else {
        eprintln!("bench-monorepo: wrote target/bench-results.md");
    }
    println!("{table}");

    if keep {
        eprintln!("bench-monorepo: tempdir kept at {}", tmp.display());
    }
    ExitCode::SUCCESS
}

#[derive(Debug)]
struct Row {
    label: String,
    duration: Option<Duration>,
    exit: Option<i32>,
}

impl Row {
    fn not_available(name: &str) -> Self {
        Self {
            label: name.to_owned(),
            duration: None,
            exit: None,
        }
    }
}

fn measure(label: &str, dir: &Path, argv: &[&str]) -> Row {
    let start = Instant::now();
    let result = Command::new(argv[0])
        .args(&argv[1..])
        .current_dir(dir)
        .output();
    let duration = start.elapsed();
    match result {
        Ok(out) => Row {
            label: label.to_owned(),
            duration: Some(duration),
            exit: Some(out.status.code().unwrap_or(-1)),
        },
        Err(_) => Row::not_available(label),
    }
}

fn render_table(total_files: usize, rows: &[Row]) -> String {
    let mut out = String::new();
    out.push_str("# Betterhook monorepo benchmark\n\n");
    let _ = writeln!(
        out,
        "Synthetic repo with {total_files} files across {} packages.\n",
        PACKAGES.len()
    );
    out.push_str("| Run | Wall time | Exit |\n|---|---|---|\n");
    for r in rows {
        let time = r
            .duration
            .map_or_else(|| "n/a".to_owned(), |d| format!("{} ms", d.as_millis()));
        let exit = r.exit.map_or_else(|| "n/a".to_owned(), |c| c.to_string());
        let _ = writeln!(out, "| {} | {time} | {exit} |", r.label);
    }
    out.push_str("\nGenerated by `cargo xtask bench-monorepo`.\n");
    out
}

fn which(bin: &str) -> bool {
    Command::new(bin)
        .arg("--version")
        .output()
        .is_ok_and(|o| o.status.success())
}

/// Build a small synthetic repo with `PACKAGES.len()` packages, each
/// containing `FILES_PER_PACKAGE` `.txt` files plus a betterhook config
/// that runs an instant noop hook.
fn generate_repo(dir: &Path) -> std::io::Result<()> {
    std::fs::create_dir_all(dir)?;
    Command::new("git")
        .arg("init")
        .arg("-q")
        .current_dir(dir)
        .status()?;
    for pkg in PACKAGES {
        let pkg_dir = dir.join("apps").join(pkg);
        std::fs::create_dir_all(&pkg_dir)?;
        for i in 0..FILES_PER_PACKAGE {
            let file = pkg_dir.join(format!("file_{i:05}.txt"));
            std::fs::write(file, b"hello\n")?;
        }
    }
    let cfg = r#"[meta]
version = 1

[hooks.pre-commit.jobs.noop]
run = "true"
glob = ["*.txt"]
concurrent_safe = true
"#;
    std::fs::write(dir.join("betterhook.toml"), cfg)?;
    Command::new("git")
        .args(["add", "-A"])
        .current_dir(dir)
        .status()?;
    Command::new("git")
        .args([
            "-c",
            "user.email=bench@betterhook",
            "-c",
            "user.name=bench",
            "commit",
            "-q",
            "-m",
            "init",
        ])
        .current_dir(dir)
        .status()?;
    Ok(())
}

fn tempdir() -> std::io::Result<PathBuf> {
    let base = std::env::temp_dir().join(format!("betterhook-bench-{}", std::process::id()));
    if base.exists() {
        std::fs::remove_dir_all(&base)?;
    }
    std::fs::create_dir_all(&base)?;
    Ok(base)
}
